# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROe77z6bsMQQL2e5bKz4Pskgfd0MsJCF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, accuracy_score
from sklearn.cluster import KMeans

df = pd.read_csv("datasetterakhir12.csv", sep=';')

print(df.head())
print(df.info())

# Distribusi jenis kelamin
print(df["Jenis Kelamin"].value_counts())

# Clean and convert 'Jumlah Buku yang dibaca dalam 1 bulan' to numeric
df['Jumlah Buku yang dibaca dalam 1 bulan'] = df['Jumlah Buku yang dibaca dalam 1 bulan'].str.replace('Tidak Membaca Buku', '0', case=False).str.replace(r'\s*[Bb]uku', '', regex=True).str.strip().astype(int)

# Rata-rata jumlah buku
print(df["Jumlah Buku yang dibaca dalam 1 bulan"].mean())

# Visualisasi
df["Genre Buku Yang Sering Dibaca"].value_counts().plot(kind='bar')
plt.title("Distribusi Genre Buku")
plt.show()

"""Hasil analisis deskriptif menunjukkan bahwa:

Mayoritas responden adalah mahasiswa perempuan.

Genre buku yang paling banyak diminati adalah fiksi.

Alasan utama membaca adalah untuk hiburan.

Sebagian besar mahasiswa membaca di rumah.

Tingkat kegemaran membaca berada pada kategori menengah hingga tinggi (skala 7–9).

Hal ini menunjukkan bahwa aktivitas membaca pada mahasiswa cenderung dilakukan sebagai kegiatan rekreatif dibandingkan akademik.
"""

